### PR TITLE
feat: promote experimental commands

### PR DESCRIPTION
**Pull request by wmalik**
## What this PR does / why we need it:

The following commands are being promoted out of experimental:

* `experimental metadata` -> `debug show metadata`
* `experimental globals` -> `debug show globals`
* `experimental generate debug` -> `debug show generate-origins`
* `experimental run-env` -> `debug show runtime-env`
* `experimental run-graph` -> `debug render run-graph`

## Does this PR introduce a user-facing change?

```
Yes, users must switch to the new command path for the above mentioned commands.
```

### CODE REVIEW

**Comment by soerenmartius** [comment]
@wmalik I just looked at the docs and we are referencing some of the comments in written text in the docs. We should make sure to update those also to not cause any outdated docs.

**Comment by wmalik** [comment]
> @wmalik I just looked at the docs and we are referencing some of the comments in written text in the docs. We should make sure to update those also to not cause any outdated docs.

@soerenmartius oh good catch, will update that as part of this PR

**Comment by soerenmartius** [comment]
> > @wmalik I just looked at the docs and we are referencing some of the comments in written text in the docs. We should make sure to update those also to not cause any outdated docs.
> 
> @soerenmartius oh good catch, will update that as part of this PR

awesome thank you!

**Review by i4ki — APPROVED** [review]
LGTM

**Pull request merged**
