### PR TITLE
fix: use stack environ for the cmd lookpath

### PR DESCRIPTION
**Pull request by i4ki**
When executing the commands provided to `terramate run`, the actual path of the program was being resolved using Terramate's own `PATH` environment variable instead of the stack's environment (that could be changed using `terramate.config.run.env.PATH` configuration.

The fix ensures that the program to be invoked is resolved using the stack's environment.

### CODE REVIEW

**Review by mariux — APPROVED** [review]
lgtm

**Comment by i4ki** [comment]
@soerenmartius I improve the docs regarding this behavior. Can you have a look?

**Comment by i4ki** [comment]
@soerenmartius what to do here regarding the LICENSE?

**Review by mariux — APPROVED** [review]
lgtm

**Pull request merged**
