### PR TITLE
fix: mishandled error leading to nil dereference in metadata

### PR DESCRIPTION
**Pull request by snakster**
## What this PR does / why we need it:

This fixes a potential crash when trying to obtain the pull request metadata associated with a Github repository.

## Does this PR introduce a user-facing change?

```
no
```

### CODE REVIEW

**Review by i4ki — APPROVED** [review]
LGTM

**Comment by i4ki** [comment]
cases to be checked:
- local commit is not pushed, then getPR... will return an error
- commit is pushed but not associated with any PR
- commit is pushed but associated with many PRs
- any other?

@snakster did you validate these cases?

**Comment by snakster** [comment]
@i4ki 
* local commit is not pushed, then getPR... will return an error: ✅ 
```
s1 % terramate run --sync-deployment -- echo "deploying" 
2024-05-07T17:44:31+02:00 WRN failed to retrieve commit information from GitHub API error="GET https://api.github.com/repos/snakster/metadata-test/commits/43f671846957491c579ed5f7b4d41a106445cb3c: 422 No commit found for SHA: 43f671846957491c579ed5f7b4d41a106445cb3c []" github_repository=snakster/metadata-test head_commit=43f671846957491c579ed5f7b4d41a106445cb3c normalized_repository=github.com/snakster/metadata-test
2024-05-07T17:44:31+02:00 WRN failed to retrieve pull requests associated with HEAD error="GET https://api.github.com/repos/snakster/metadata-test/commits/43f671846957491c579ed5f7b4d41a106445cb3c/pulls?per_page=1: 422 No commit found for SHA: 43f671846957491c579ed5f7b4d41a106445cb3c []" commit=43f671846957491c579ed5f7b4d41a106445cb3c github_repository=snakster/metadata-test
terramate: Entering stack in /s1
terramate: Executing command "echo deploying"
deploying
```
* commit is pushed but not associated with any PR: ✅ 
```
s1 % terramate run --sync-deployment -- echo "deploying"
terramate: Entering stack in /s1
terramate: Executing command "echo deploying"
deploying
```

* commit is pushed but associated with many PRs: ✅ 
```
s1 % terramate run --sync-deployment -- echo "deploying"                                                            
terramate: Entering stack in /s1
terramate: Executing command "echo deploying"
deploying
```

**Review by i4ki — APPROVED** [review]
LGTM

**Pull request merged**
