### PR TITLE
feat: generate files in working directory.

### PR DESCRIPTION
**Pull request by i4ki**
## What this PR does / why we need it:

Makes Terramate respects working directory and `-C/--chdir` when generating files.

## Which issue(s) this PR fixes:
none

## Does this PR introduce a user-facing change?
```
yes, add a new feature.
```

### CODE REVIEW

**Review by soerenmartius — DISMISSED** [review]
LGTM, great improvement! Could you add this to the docs as well? Thanks!

**Comment by i4ki** [comment]
@soerenmartius https://github.com/terramate-io/terramate-docs/pull/41

**Review by snakster — APPROVED** [review]
Nice change! 👍

**Review by soerenmartius — APPROVED** [review]
LGTM

**Pull request merged**
