### PR TITLE
feat: implements cloud info command

### PR DESCRIPTION
**Pull request by i4ki**
```
$ terramate experimental cloud info
status: signed in
provider: Google Social Provider
email: tiago.natel@....
organizations: Terramate
```

Verbose output:
```
$ terramate experimental cloud info
credentials loaded from /home/i4k/.terramate.d/credentials.tmrc.json
status: signed in
provider: Google Social Provider
email: tiago.natel@....
organizations: Terramate
next token refresh in: 51m9.2540602s
```

When using [GitHub OIDC](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers):

```
$ terramate experimental cloud info
status: signed in
provider: GitHub Actions OIDC
owner: terramate-io
repository: terramate-io/terramate
organizations: Terramate
```

### CODE REVIEW

**Review by switchdk — APPROVED** [review]
Nice work @i4ki 🙌🏻

**Review by mariux — DISMISSED** [review]
the behaviour does not match what is requested in the ticket:

```
status: signed in
provider: GitHub Actions OIDC
owner: terramate-io
repository: terramate-io/terramate
organizations: none
```

when you are not signed in to any organization, you are not signed in at all.. so this is the `unauthorized` state.. you can not do any calls to the API as they will all fail with unauthorized or forbidden.

**Comment by i4ki** [comment]
@mariux @switchdk please review again.

**Review by switchdk — APPROVED** [review]
Very nice, thanks @i4ki

**Pull request merged**
