### PR TITLE
feat: add env vars for common cli and run flags

### LINKED ISSUE #1841: [FEATURE] Support environment variable configuration for CLI commands
**Is your feature request related to a problem? Please describe.**

A common pattern in CICD pipelines is to use environment variables to configure the behavior of a predefined script. Our team leverages this pattern and generally make heavy use of variable inheritance to configure individual behaviors at various layers of the pipeline config hierarchy (e.g. template, pipeline, base job, job).

We would like to see first-class support for this pattern in the terramate CLI in order to simplify our own scripts. There is already precedent for this with the [`TM_DISABLE_SAFEGUARDS`](https://github.com/terramate-io/terramate/blob/f730f9c3f07dd743695166a1b9bc804eeccfd768/cmd/terramate/cli/cli.go#L306) variable and the code change is trivial.

**Describe the solution you'd like**

Support additional environment variables to configure common terramate CLI flags found [here](https://github.com/terramate-io/terramate/blob/f730f9c3f07dd743695166a1b9bc804eeccfd768/cmd/terramate/cli/cli.go#L104-L114). Examples would be `TM_CHDIR` for `--chdir` or `TM_TAGS` for `--tags` etc.

We would like to also see a similar implementation for subcommand flags (e.g. `TM_RUN_PARALLEL=5` for `terramate run` etc.) but understand that this may come in a different form. For example, Terraform uses `TF_CLI_ARGS_<subcommand>=<flags>`, which I personally don't love but it works. However this method doesn't work well with inheritance given that it is a all-or-nothing definition.

I'm also not sure how this would work for shared subcommands such as `terramate run` and `terramate script run` since ideally we'd want the vars to be shared, but perhaps run args should be a special case.

Command-line flags should take precedence over env vars. It appears this is already the default behavior for the cli parser.

**Describe alternatives you've considered**

We build the terramate flags directly in the common scripts, which works fine but is messy. Basic example below (Gitlab CI). We'd like to keep the interface that is used by the Project Pipeline but get rid of custom logic in the Shared Template.

```yaml
# Shared template
.base:
  before_script:
  - export TM_CLI_ARGS="${TM_TAGS:+--tags $TM_TAGS} <etc>"
  - export TM_RUN_ARGS="${TM_RUN_PARALLEL:+--parallel $TM_RUN_PARALLEL} <etc>"

.init:
  extends: .base
  script:
  - terramate $TM_CLI_ARGS run $TM_RUN_ARGS terraform init
...
```
```yaml
# Project pipeline
include:
- project: shared-templates
  file: terramate.yml

# Run all terramate run commands with parallelism=5
variables:
  TM_RUN_PARALLEL: '5'

# Base jobs inherited by init, plan, apply etc. for consistency
.dev:
  variables:
    TM_TAGS: dev

.stg:
  variables:
    TM_TAGS: stg

init-dev:
  extends: [.init, .dev]

init-stg:
  extends: [.init, .stg]

...
```

**Additional context**
I'd be open to making this contribution

### PR DESCRIPTION
**Pull request by bgrams**
## What this PR does / why we need it:
Support use of environment variables to configure Terramate CLI commands.

## Which issue(s) this PR fixes:
Fixes #1841

## Special notes for your reviewer:
* This involved a refactor to group flags logically in order to take advantage of Kong's `envprefix` [struct tag](https://github.com/alecthomas/kong?tab=readme-ov-file#supported-tags)
* Env vars were not added for hidden flags
* An attempt was made to preserve ordering of flags, but there are some changes. For example `--eval` and `--terragrunt` now come after `--parallel` for `terramate run`. This is very minor and should only have a bearing on help output, but doc pages may need updating.

## Does this PR introduce a user-facing change?
Yes, adds an alternative method of configuring the Terramate CLI

### CODE REVIEW

**Comment by i4ki** [comment]
Hey @bgrams, can you rebase on top of `main`? What do you think of shipping this in the next `v0.11.0` release?

**Comment by bgrams** [comment]
Hey @i4ki, that sounds good 👍 I synced the fork but it looks like that created a merge commit. Let me undo that and rebase. I'll also update the commit signature for https://github.com/terramate-io/terramate/pull/1850/commits/9fab73f868ac965799d3e24aec5e1cd3559c383d.

**Comment by i4ki** [comment]
Hey @bgrams 

Can you fix the conflict? Sorry about that.
I manually testes and also added some basic tests here https://github.com/terramate-io/terramate/pull/1910
and everything seems to be working fine. 

So once rebased, let me know again to get this merged ASAP.

**Review by i4ki — APPROVED** [review]
LGTM

**Comment by i4ki** [comment]
Thank you @bgrams!

**Pull request merged**
